/**
 * orchestratorRoutes.js — API routes for the Orchestrator Agent system.
 * 
 * Endpoints for plan generation, daily views, deliverable management,
 * rollover enforcement, progress tracking, and unified dashboard data.
 */

const express = require('express');
const router = express.Router();
const planStore = require('../data/planStore');
const orchestratorService = require('../services/orchestratorService');
const orchestratorBridge = require('../services/orchestratorBridge');

// ── Generate Plan ─────────────────────────────────────────────────────────────
// Creates a new weekly or monthly plan from workspace project management data.
router.post('/generate-plan', (req, res) => {
    const { workspaceId, timeframe } = req.body;

    if (!workspaceId) {
        return res.status(400).json({ success: false, error: 'workspaceId is required.' });
    }

    const validTimeframes = ['week', 'month'];
    const tf = validTimeframes.includes(timeframe) ? timeframe : 'week';

    const plan = orchestratorService.generatePlan(workspaceId, tf);

    if (!plan) {
        return res.status(404).json({
            success: false,
            error: 'Workspace not found or has no project management data.'
        });
    }

    res.status(201).json({
        success: true,
        message: `${tf === 'week' ? 'Weekly' : 'Monthly'} plan generated by Orchestrator Agent.`,
        plan
    });
});

// ── Get Plan by ID ────────────────────────────────────────────────────────────
router.get('/plan/:planId', (req, res) => {
    const plan = planStore.getPlan(req.params.planId);
    if (!plan) {
        return res.status(404).json({ success: false, error: 'Plan not found.' });
    }

    res.status(200).json({ success: true, plan });
});

// ── Get All Plans for a Workspace ─────────────────────────────────────────────
router.get('/plans/:workspaceId', (req, res) => {
    const plans = planStore.getPlansByWorkspace(req.params.workspaceId);

    res.status(200).json({
        success: true,
        workspaceId: req.params.workspaceId,
        totalPlans: plans.length,
        plans
    });
});

// ── Get Active Plan for a Workspace ───────────────────────────────────────────
router.get('/active-plan/:workspaceId', (req, res) => {
    const plan = planStore.getActivePlan(req.params.workspaceId);

    if (!plan) {
        return res.status(404).json({
            success: false,
            error: 'No active plan found for this workspace. Generate one first.'
        });
    }

    res.status(200).json({ success: true, plan });
});

// ── Daily View ────────────────────────────────────────────────────────────────
// Returns all deliverables assigned to a specific day.
// Query param: ?date=YYYY-MM-DD (defaults to today)
router.get('/daily/:planId', (req, res) => {
    const date = req.query.date || planStore.todayKey();
    const dailyView = planStore.getDailyView(req.params.planId, date);

    if (!dailyView) {
        return res.status(404).json({ success: false, error: 'Plan not found.' });
    }

    res.status(200).json({ success: true, ...dailyView });
});

// ── Update Deliverable ────────────────────────────────────────────────────────
// Supports: status changes (pending → in-progress → completed), field updates.
router.patch('/deliverable/:planId/:deliverableId', (req, res) => {
    const { planId, deliverableId } = req.params;
    const updates = req.body;

    if (!updates || Object.keys(updates).length === 0) {
        return res.status(400).json({ success: false, error: 'No updates provided.' });
    }

    // Validate status if provided
    const validStatuses = ['pending', 'in-progress', 'completed', 'rolled-over'];
    if (updates.status && !validStatuses.includes(updates.status)) {
        return res.status(400).json({
            success: false,
            error: `Invalid status. Must be one of: ${validStatuses.join(', ')}`
        });
    }

    const updated = planStore.updateDeliverable(planId, deliverableId, updates);

    if (!updated) {
        return res.status(404).json({ success: false, error: 'Plan or deliverable not found.' });
    }

    res.status(200).json({
        success: true,
        message: `Deliverable "${updated.title}" updated.`,
        deliverable: updated
    });
});

// ── Roll Forward Incomplete ───────────────────────────────────────────────────
// Moves yesterday's incomplete deliverables to today.
// Optional body: { fromDate: "YYYY-MM-DD" } to roll from a specific date.
router.post('/rollforward/:planId', (req, res) => {
    const fromDate = req.body.fromDate || undefined; // undefined = yesterday

    const result = planStore.rollForwardIncomplete(req.params.planId, fromDate);

    if (!result) {
        return res.status(404).json({ success: false, error: 'Plan not found.' });
    }

    res.status(200).json({
        success: true,
        message: result.rolledCount > 0
            ? `${result.rolledCount} deliverable(s) rolled from ${result.fromDate} to ${result.toDate}.`
            : `All deliverables for ${result.fromDate} were completed. Nothing to roll forward.`,
        ...result
    });
});

// ── Progress ──────────────────────────────────────────────────────────────────
// Returns overall plan progress + daily breakdown.
router.get('/progress/:planId', (req, res) => {
    const overall = planStore.getOverallProgress(req.params.planId);

    if (!overall) {
        return res.status(404).json({ success: false, error: 'Plan not found.' });
    }

    // Also include today's progress
    const todayProgress = planStore.getDailyProgress(req.params.planId, planStore.todayKey());

    res.status(200).json({
        success: true,
        overall,
        today: todayProgress
    });
});

// ── Unified Dashboard ─────────────────────────────────────────────────────────
// Returns everything the dashboard needs in a single call:
// Active plan summary, today's tasks, overall progress, upcoming deadlines,
// recent completions, rolled-over items, and orchestrator message.
router.get('/dashboard/:workspaceId', (req, res) => {
    const dashboardData = orchestratorService.getDashboardData(req.params.workspaceId);

    res.status(200).json({
        success: true,
        ...dashboardData
    });
});

// ── Run Full Orchestration Pipeline ───────────────────────────────────────────
// Triggers Plan → Execute → Synthesize for a workspace.
router.post('/run', (req, res) => {
    const { workspaceId, query } = req.body;

    if (!workspaceId) {
        return res.status(400).json({ success: false, error: 'workspaceId is required.' });
    }
    if (!query || !query.trim()) {
        return res.status(400).json({ success: false, error: 'query is required.' });
    }

    const run = orchestratorBridge.runOrchestration(workspaceId, query.trim());

    if (!run) {
        return res.status(404).json({
            success: false,
            error: 'Workspace not found. Cannot run orchestration.'
        });
    }

    res.status(201).json({
        success: true,
        message: 'Orchestration pipeline completed.',
        run
    });
});

// ── Orchestration Run History ─────────────────────────────────────────────────
// Returns all orchestration runs for a workspace, newest first.
router.get('/runs/:workspaceId', (req, res) => {
    const runs = orchestratorBridge.getOrchestrationHistory(req.params.workspaceId);

    res.status(200).json({
        success: true,
        workspaceId: req.params.workspaceId,
        totalRuns: runs.length,
        runs
    });
});

// ── Single Orchestration Run ──────────────────────────────────────────────────
// Returns the full result of a single orchestration run.
router.get('/run/:runId', (req, res) => {
    const run = orchestratorBridge.getOrchestrationRun(req.params.runId);

    if (!run) {
        return res.status(404).json({ success: false, error: 'Orchestration run not found.' });
    }

    res.status(200).json({ success: true, run });
});

module.exports = router;
