import { AgentOutput } from "../contracts";
import { ToolOutput, GeneratedArtifact } from "../mcp";

/**
 * Identifies what type of execution target a step represents.
 */
export type ExecutionTargetType =
  | "agent"
  | "tool";

/**
 * A single unit of work in an execution plan.
 * Generated by the Planner and executed by the Executor.
 */
export interface ExecutionStep {
  /**
   * Unique identifier for this step.
   */
  id: string;

  /**
   * Whether this step targets an Agent or an MCP Tool.
   */
  targetType: ExecutionTargetType;

  /**
   * Agent ID or Tool name.
   *
   * Examples:
   *  developer
   *  legal
   *  generate_docx
   *  generate_image
   */
  target: string;

  /**
   * Task that the target must perform.
   */
  task: string;

  /**
   * Generic arguments supplied by the planner.
   *
   * These remain provider-agnostic and are translated
   * by ToolArgumentResolvers into the format expected
   * by the target MCP tool.
   *
   * Examples:
   * {
   *   fileName: "legal-opinion.docx"
   * }
   */
  arguments?: Record<string, unknown>;

  /**
   * IDs of steps that must complete before this step can execute.
   */
  dependsOn?: string[];

  /**
   * Whether this step is eligible for parallel execution.
   * (Not implemented in MVP.)
   */
  allowParallel?: boolean;

  /**
   * Maximum retry attempts.
   * (Retries not implemented yet.)
   */
  maxRetries?: number;

  /**
   * Execution timeout in milliseconds.
   */
  timeoutMs?: number;

  /**
   * Optional execution constraints.
   */
  constraints?: string[];
}

/**
 * Ordered execution plan produced by the Planner.
 */
export interface ExecutionPlan {
  /**
   * Original user request.
   */
  query: string;

  /**
   * Ordered execution steps.
   */
  steps: ExecutionStep[];
}

/**
 * Result returned after executing one step.
 */
export interface StepResult {
  /**
   * Step identifier.
   */
  stepId: string;

  /**
   * Agent ID or Tool name that executed this step.
   */
  executor: string;

  /**
   * Original task.
   */
  task: string;

  /**
   * Whether execution succeeded.
   */
  success: boolean;

  /**
   * Number of attempts used.
   */
  attempts: number;

  /**
   * Execution duration.
   */
  durationMs: number;

  /**
   * Agent or Tool output.
   */
  output: AgentOutput | ToolOutput;

  /**
   * Optional execution error.
   */
  error?: string;
}

/**
 * Shared state passed through orchestration.
 * This will later support memory, tools and RAG
 * without changing the planner or executor interfaces.
 */
export interface ExecutionContext {
  /**
   * Original user query.
   */
  query: string;

  /**
   * Execution plan generated by the planner.
   */
  plan: ExecutionPlan;

  /**
   * Results produced so far.
   */
  results: StepResult[];

  /**
   * Reserved for future shared memory.
   */
  memory?: Record<string, unknown>;

  /**
   * Reserved for execution metadata.
   */
  metadata?: Record<string, unknown>;
}

/**
 * Final orchestration output.
 */
export interface OrchestrationResult {
  /**
   * Final execution context.
   */
  context: ExecutionContext;

  /**
   * Final CEO response.
   */
  finalOutput: AgentOutput;

  /**
   * Every downloadable artifact generated during
   * orchestration.
   *
   * The CEO only references these artifacts in its
   * synthesized response. The Orchestrator owns
   * returning them to the caller.
   */
  attachments: GeneratedArtifact[];
}

/**
 * Planner output.
 */
export interface PlanningResult {
  plan: ExecutionPlan;

  reasoning?: string;
}